import 'package:flutter_test/flutter_test.dart';

import 'package:luna_pos/features/receipt/models/receipt_data.dart';
import 'package:luna_pos/features/receipt/models/receipt_line_item.dart';
import 'package:luna_pos/features/store_settings/models/store_settings.dart';
import 'package:luna_pos/features/receipt/models/transaction_response.dart';
import 'package:luna_pos/features/receipt/receipt_builder.dart';
import 'package:luna_pos/features/user/models/user.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late ReceiptBuilder builder;

  setUp(() async {
    builder = await ReceiptBuilder.create();
  });

  ReceiptData sampleReceiptData({
    int discountAmount = 0,
    int changeAmount = 0,
  }) {
    return ReceiptData(
      brandName: 'Luna Cafe',
      branchName: 'Cabang Sudirman',
      branchAddress: 'Jl. Sudirman No. 10, Jakarta',
      branchPhone: '021-1234567',
      cashierName: 'Budi Santoso',
      transactionId: 'TXN-001',
      transactionDate: DateTime(2026, 7, 11, 14, 30),
      paymentMethod: 'CASH',
      items: const [
        ReceiptLineItem(
          title: 'Es Teh Manis',
          quantity: 2,
          note: 'less ice',
          lineTotal: 16000,
        ),
        ReceiptLineItem(
          title: 'Nasi Goreng Spesial dengan Telur Mata Sapi',
          quantity: 1,
          lineTotal: 35000,
        ),
      ],
      subtotalAmount: 51000,
      discountAmount: discountAmount,
      totalAmount: 51000 - discountAmount,
      cashTendered: 100000,
      changeAmount: changeAmount,
      thankYouNote: 'Terima kasih!',
    );
  }

  test('generated bytes are non-empty', () {
    final bytes = builder.build(sampleReceiptData());

    expect(bytes, isNotEmpty);
  });

  test('receipt includes mandatory header and body fields', () {
    final text = decodeReceiptText(builder.build(sampleReceiptData()));

    expect(text, contains('Luna Cafe'));
    expect(text, contains('Cabang Sudirman'));
    expect(text, contains('Jl. Sudirman No. 10, Jakarta'));
    expect(text, contains('021-1234567'));
    expect(text, contains('Budi Santoso'));
    expect(text, contains('TXN-001'));
    expect(text, contains('Es Teh Manis'));
    expect(text, contains('x2'));
    expect(text, contains('less ice'));
    expect(text, contains('Rp 16.000'));
    expect(text, contains('Rp 51.000'));
    expect(text, contains('Terima kasih!'));
  });

  test('receipt includes item note and line total', () {
    final text = decodeReceiptText(builder.build(sampleReceiptData()));

    expect(text, contains('Note: less ice'));
    expect(text, contains('Es Teh Manis'));
    expect(text, contains('x2'));
    expect(text, contains('Rp 16.000'));
  });

  test('receipt omits zero discount and prints Kembalian as negative zero', () {
    final text = decodeReceiptText(
      builder.build(sampleReceiptData(discountAmount: 0, changeAmount: 0)),
    );

    expect(text, isNot(contains('Discount')));
    expect(text, contains('Kembalian'));
    expect(text, contains('-Rp 0'));
    expect(text, contains('Bayar'));
    expect(text, contains('Subtotal'));
    expect(text, contains('TOTAL'));
  });

  test('receipt includes discount and change when non-zero', () {
    final text = decodeReceiptText(
      builder.build(sampleReceiptData(discountAmount: 5000, changeAmount: 44000)),
    );

    expect(text, contains('Discount'));
    expect(text, contains('Kembalian'));
    expect(text, contains('Rp 5.000'));
    expect(text, contains('-Rp 44.000'));
  });

  test('fromCheckout maps transaction, store, and cashier fields', () {
    final data = ReceiptData.fromCheckout(
      txn: TransactionResponse(
        id: 'TXN-99',
        method: 'CASH',
        createdAt: DateTime(2026, 7, 11, 9, 15),
        items: const [
          ReceiptLineItem(
            title: 'Kopi Susu',
            quantity: 1,
            lineTotal: 18000,
          ),
        ],
        subtotalAmount: 18000,
        totalAmount: 18000,
        cashTendered: 20000,
        changeAmount: 2000,
      ),
      store: const StoreSettings(
        brandName: 'Luna Coffee',
        branchName: 'Cabang Kemang',
        branchAddress: 'Jl. Kemang Raya 5',
        branchPhone: '021-7654321',
        thankYouNote: 'Sampai jumpa!',
      ),
      cashier: const User(
        id: 'u1',
        name: 'Ani',
        email: 'ani@example.com',
        merchantId: 'merchant-1',
        roles: ['cashier'],
      ),
    );

    final text = decodeReceiptText(builder.build(data));

    expect(text, contains('Luna Coffee'));
    expect(text, contains('Cabang Kemang'));
    expect(text, contains('Ani'));
    expect(text, contains('TXN-99'));
    expect(text, contains('Kopi Susu'));
    expect(text, contains('Sampai jumpa!'));
  });

  test('long titles and notes do not crash the builder', () {
    final bytes = builder.build(
      sampleReceiptData().copyWith(
        items: [
          const ReceiptLineItem(
            title:
                'Menu Spesial Hari Ini Dengan Banyak Topping Dan Saus Tambahan',
            quantity: 3,
            note:
                'extra spicy no onion less sugar more ice please pack separately',
            lineTotal: 99000,
          ),
        ],
      ),
    );

    expect(bytes, isNotEmpty);
    final text = decodeReceiptText(bytes);
    expect(text, contains('Menu Spesial'));
    expect(text, contains('Note:'));
  });

  test('receipt omits cash lines for qris payment', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(
          paymentMethod: 'QRIS',
          cashTendered: null,
          changeAmount: 0,
        ),
      ),
    );

    expect(text, contains('Metode'));
    expect(text, contains('QRIS'));
    expect(text, isNot(contains('Bayar')));
    expect(text, isNot(contains('Kembalian')));
  });

  test('receipt includes order option name when provided', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(orderOptionName: 'Take Away'),
      ),
    );

    expect(text, contains('Tipe'));
    expect(text, contains('Take Away'));
  });

  test('cash payment Bayar line has no a2Rp corruption', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(
          cashTendered: 50000,
          changeAmount: 15000,
          totalAmount: 35000,
        ),
      ),
    );

    expect(text, contains('Bayar'));
    expect(text, contains('Rp 50.000'));
    expect(text, isNot(contains('a2Rp')));
  });

  test('million-rupiah Bayar and Kembalian fit on one line', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(
          cashTendered: 1000000,
          changeAmount: 0,
          totalAmount: 1000000,
        ),
      ),
    );

    expect(text, contains('Rp 1.000.000'));
    expect(text, isNot(contains('a2Rp')));
    expect(text, isNot(contains('BayarRp')));
    expect(text, isNot(contains('KembalianRp')));
    expect(text, isNot(contains('Bayar a')));
    expect(text, isNot(contains('Kembalian a')));
  });

  test('Kembalian prints as negative value', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(
          cashTendered: 50000,
          changeAmount: 15000,
          totalAmount: 35000,
        ),
      ),
    );

    expect(text, contains('Kembalian'));
    expect(text, contains('-Rp 15.000'));
  });

  test('zero change prints Kembalian as negative zero', () {
    final text = decodeReceiptText(
      builder.build(
        sampleReceiptData().copyWith(
          cashTendered: 51000,
          changeAmount: 0,
          totalAmount: 51000,
        ),
      ),
    );

    expect(text, contains('Bayar'));
    expect(text, contains('Kembalian'));
    expect(text, contains('-Rp 0'));
  });

  test('builder output is deterministic for the same input', () {
    final data = sampleReceiptData();
    final first = builder.build(data);
    final second = builder.build(data);

    expect(first, equals(second));
  });
}
